---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: pedigree-amazonlinux2-base
    image: pedigreetechnologies/docker-amazonlinux2-base:latest
    privileged: true
    pre_build_image: true
provisioner:
  name: ansible
  log: true
verifier:
  name: ansible
lint: |
  set -e
  ansible-lint
